### PR TITLE
Close file descriptors on failure

### PR DESCRIPTION
**Pull request by raphinesse**
This ensures that any file descriptors opened by `read-chunk` are closed before the function returns/resolves. Prior to this change, file descriptors would remain open if `fs.read` or `fs.readSync` would throw.

Full disclosure: The module I used to handle this is my own. I know of no other established module to handle the use case at hand.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you add an async and sync regression test?

**Comment by raphinesse** [comment]
It's tricky. `with-open-file` has tests that ensure that the opened file descriptor is always closed. But I'll give it another try.

**Comment by raphinesse** [comment]
@sindresorhus OK, so I finally have working regression tests. Naturally they are not particularly pretty, as we have to test global effects.

I thought about moving them to a separate test file for stronger isolation, but I wasn't sure. What do you think?

**Comment by sindresorhus** [comment]
> I thought about moving them to a separate test file for stronger isolation, but I wasn't sure. What do you think?

👍

**Comment by raphinesse** [comment]
Do you have any suggestions for suitable file/test-suite names? I'm kinda lost here...

**Comment by raphinesse** [comment]
Tests are now split up into two files and moved to `test/`. Splitting the tests up, made for cleaner tests overall :+1:

What do you think, @sindresorhus?

**Comment by sindresorhus** [comment]
Nice work! Looks good :)

**Pull request merged**
